<a href="https://www.kaggle.com/code/devdootji/devdoot?scriptVersionId=283157245" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**First Program**

In [ ]:
print("Hello Devdoots! I am Divyansh.")

Hello Devdoots! I am Divyansh.


**Variables Assingment**

In [ ]:
first_number = 20
second_number = 40
addition = first_number + second_number
print(f"Sum of numbers is :",addition)

Sum of numbers is : 60


**Input & Output with int**

In [ ]:
first_num = int(input("Enter your first Number :"))
Second_num = int(input("Enter your Second Number :"))
print(f"sum of numbers is :",first_num + Second_num)
print(f"subtration of numbers is :",first_num - Second_num)
print(f"Multiplication of numbers is :",first_num * Second_num)
print(f"Division of numbers is :",first_num / Second_num)
print(f"float of numbers is :",first_num // Second_num)
print(f"Exponential of numbers is :",first_num ** Second_num)

Enter your first Number :5
Enter your Second Number :3
sum of numbers is : 8
subtration of numbers is : 2
Multiplication of numbers is : 15
Division of numbers is : 1.6666666666666667
float of numbers is : 1
Exponential of numbers is : 125


**Input and Output with string**

In [5]:
num1 = input("enter a number :")
num2 = input("enter a number : ")
# strings ko jodna concatination kahlata hai
print(f"concatination of two numbers is :",num1 + num2)

enter a number :1
enter a number : 2
concatination of two numbers is : 12


**Data types & Rules of variables declartion**

In [ ]:
'''1 int
2 string
3 boolean
4 float
5 set
6 list
7 None
8 bytes
9 bytesarry
10 dictneries'''
a = 10
b = "10"
print(f"a ka type",type(a))
print(f"b ka type",type(b))
'''
first letter of variable must be alphabet or underscore.
no space allowed
no spwcial charecter allowed expect underscore.
no keyword allowed (reserve words  totale 33 ex. if, break,elif,for)

'''

Read data in single line using input

In [ ]:
# these two method is only for direct input
a,b = input("enter two no. :").split()
print(a)
print(b)
# second type
c,d = input("enter two no. :").split(',')
print(c)
print(d)
# method for typecasting
e,f = map(int,input("Enter Two No").split())
print(e)
print(f)


# New Section

**Print Method**

In [ ]:
a =100
b = 20
print("value is ",a,b ,sep=":",end = "........")
# Formated string
c =int(input("enter no :"))
d =int(input("enter no :"))
add = c+d
# %d,%i for int, and %f for float and %s for string
print("Addition of %d and %d is %d"%(c,d,add))

**if else condition**

In [ ]:
age = int(input("Enter your age :"))
if age >= 18:
  print("Hurry! You can vote now.")
else:
  print("Sorry! You are not eligible.")

number check positive,negative, zero

In [ ]:
num = int(input("Enter a no :"))
if num > 0 :
  print("Number is Positive.",num)
elif num<0 :
  print("Number is Negative.",num)
else:
  print("Number is Zero.",num)

**loops While and For**

In [ ]:
num  = 1
while num <=10:
  print(num)
  num=num+1

In [ ]:
# for printig 10 to 1
num = 10
while num >=1:
  print(num)
  num = num -1

In [ ]:
# printing table using for loop
num = int(input("Enter a number : "))
for table in range(1,11,1):
  print(table, "*",num,"=",table*num)


**List with for  Loop**

In [ ]:
names = ["Balram","Ritesh","Harsh Rajbhar","Harsh Gautum","Nakul"]
for name in names :
  print("Good Morning",name,".")

**List functions**

In [ ]:
my_list = []
items = int(input("Enter no :"))
for i in range (items):
  fruit = input("Enter a fruit name :")
  my_list.append(fruit)
print(my_list)

Modifiying List

In [ ]:
friends = ["Balram", "Ritesh","Harsh"]
print(f"old list: {friends}")
friends[1] = "Dev"
print(f"New list: {friends}")

POP & Remove functions

In [ ]:
friends = ["dev","balram","ram","shyam"]
print(f"Old list : {friends}")
friends.pop()
friends.remove("dev")
print(f"New List : {friends}")

function


In [ ]:
def my_info():
  print("My name is Divyansh. My collage name is MGIMT")

my_info()
my_info()
my_info()

In [ ]:
def my_info(name,collage):
  print(f"My name is {name}. My collage name is {collage}")

my_info("Divyansh","MDIMT")
my_info("DEV","MGIMT")


function with return

In [ ]:
def my_fun(a,b):
  multi = a*b
  return multi

result=my_fun(2,6)
print(f"this is the multipilication of 2 and 6 : {result}")

Dictionary

In [ ]:
Car ={
    "Brand" : " TATA ",
    "Model" : " Nexon ",
}
print(Car)

Car["Color"] = "Red"
print(Car)

dictionary with for loop

In [ ]:
student={
    "name":"Divyansh",
    "roll_no":"73",
    "college":"MGIMT"
}
for l,m in student.items():
  print(f"key is {l} and value is {m}")

first mini project a calculater

In [ ]:
#calculater
def add(a,b):
  total_add = a+b
  return total_add

def sub(a,b):
  total_sub = a-b
  return total_sub

def multi(a,b):
  total_multi= a*b
  return total_multi
def devide(a,b):
  total_devide =a/b
  return total_devide
try :
  num1=int(input("Enter a number :"))
  num2=int(input("Enter a number :"))
  op = input("Enter an operator :")
  try:
   if op == "+":
     result_add = add(num1,num2)
     print(f"sum is {result_add}")
   elif op == "-":
     result_sub = sub(num1,num2)
     print(f"subration is {result_sub}")
   elif op == "*":
     result_multi = multi(num1,num2)
     print(f"multiplication is {result_multi}")
   elif op == "/":
     result_devide = devide(num1,num2)
     print(f"Devision is {result_devide}")
   else:
     print("Worng Input!")
  except ZeroDivisionError:
    print("You can not Devide by 0!")
except ValueError:
  print('Please enter numbers only!')

calculator with math

In [ ]:
#calculater
import math
def add(a,b):
  total_add = a+b
  return total_add

def sub(a,b):
  total_sub = a-b
  return total_sub

def multi(a,b):
  total_multi= a*b
  return total_multi
def devide(a,b):
  total_devide =a/b
  return total_devide

def sq(a):
  root = math.sqrt(a)
  return root

try :
  num1=int(input("Enter a number :"))

  op = input("Enter an operator :")
  if op !="sqrt":
    num2=int(input("Enter a number :"))

  try:
   if op == "+":
     result_add = add(num1,num2)
     print(f"sum is {result_add}")
   elif op == "-":
     result_sub = sub(num1,num2)
     print(f"subration is {result_sub}")
   elif op == "*":
     result_multi = multi(num1,num2)
     print(f"multiplication is {result_multi}")
   elif op == "/":
     result_devide = devide(num1,num2)
     print(f"Devision is {result_devide}")
   elif op == "sqrt":
     total_sqrt = sq(num1)
     print(f"Square of number is {total_sqrt}")
   else:
     print("Worng Input!")
  except ZeroDivisionError:
    print("You can not Devide by 0!")
except ValueError:
  print('Please enter numbers only!')

simple code calculator

In [ ]:
def calc():
  num1 = int(input("Enter a num :"))
  op = input("Enter an operator :")
  num2 = int(input("Enter a num :"))
  if op == "+":
    sum = num1 + num2
    return sum
  elif op == "-":
    sub = num1 - num2
    return sub

out = calc()
print(out)

Numpy

In [ ]:
import numpy as np
my_list = [10,20,49,50]
my_array = np.array(my_list)
print(f"This is a list {my_list}")
print(f"This is a array {my_array}")
result_array = my_array +5
print(f"This is my new array with 5 added : {result_array}")

numpy in action

In [ ]:
import numpy as np
array1 = np.array([9,8,7,6,5])
array2 = np.array([1,2,3,4,5])
print(f"Subrtaion of array is :",array1 - array2)

2D array

In [ ]:
import numpy as np
my_list = [
    [2,3],
    [4,5],
    [34,45]
]
my_array = np.array(my_list)
print(f""" Here is my array of 3*2 is:
{my_array}""")

print(f"""
Here is the shape of my array {my_array.shape}""")

print(f"Here is the 45 from my array {my_array[2,1]}")

result analysis using numpy

2 December 2025

In [ ]:
import numpy as np
'''rohan_marks = [50,60,85,90,53,78]
rohan_marks_array = np.array(rohan_marks)
print(f"Average of Rohan Marks is {np.mean(rohan_marks_array)}")
print(f"Max Mark of Rohan is {np.max(rohan_marks_array)}")
print(f"Min Mrak of Rohan is {np.min(rohan_marks_array)}")
print(f"Total Marks of Rohan is {np.sum(rohan_marks_array)}")'''

my_array = np.arange(1,21)
print(my_array)
reshappend_array = my_array.reshape(10,2)
print(f"{reshappend_array}")
reshappend_array2 = my_array.reshape(2,10)
print(f"{reshappend_array2}")

recall session from numpy

In [1]:
# import numpy as np
# my_list = [12,34,56,78,98]
# my_array = np.array(my_list)
# print(my_array)

import numpy as np
fav_list = [12,34,56,78,90]
fav_array = np.array(fav_list)
print(fav_array)
new_array = 10 + fav_array
print(new_array)

import numpy as np
stu1=[10,20,30]
stu2=[40,50,60]
one = np.array([stu1,stu2])
print(one)
print(one.shape)


[12 34 56 78 90]
[ 22  44  66  88 100]
[[10 20 30]
 [40 50 60]]
(2, 3)
